### ISSUE TITLE
Creating new calendars

### ISSUE THREAD

**Issue by udiudi** [northworld/google_calendar#68]
Hi,
how difficult it'll be to allow creating new calendars and not passing calendar_id?
What are the cases I should handle to allow that? and not passing calendar_id to ``Google::Calendar.new``

Any technical reason its not already supported?

**Comment by szich** [comment]
For some time now I've wanted to refactor the code so there would be a base object and a calendar factory object so it would be easier to interact with multiple calendars and work with calendar attributes.  But I haven't had the time to do it properly.  So yes, it is possible, but it will require a modest investment in time.

**Comment by udiudi** [comment]
@szich Thanks for the reply.
Could you give me some pointers to where I should look into just so I could estimate how long it'll take me?

**Comment by szich** [comment]
If all you want to do is be able to create an instance of the Google::Calendar class without passing in a calendar_id that would be easy to accomplish.  If you want to refactor the library, as I discussed above that will take a bit more time.

Either way a close look at the underling API is the best place to start:
https://developers.google.com/google-apps/calendar/v3/reference/

**Comment by szich** [comment]
It's difficult to give you a specific answer because I'm not sure exactly what you have in mind, so  it depends on what you want to accomplish.  As I mentioned above if all you want to do is modify the existing code so you can create an instance of the Google::Calendar class that involves minimal changes that will take a couple of hours at most.  If you want to refactor the library, then you will be making more changes.  The ones I have in mind (which may or may not meet your needs) involve adding a base class and updating the google calendar class to remove all of the connection plumbing and add calendar specific attributes.  Thinking about it now, it doesn't seem like to much of a heavy lift, but when refactoring code it's easy to get sucked in.

**Comment by udiudi** [comment]
Ok, thanks!
